package com.GUI;
/**
 *
 * @author caoda
 */


import com.controller.java.tickets.Ticket;
import com.controller.java.tickets.OneWayTicket;
import com.controller.java.tickets.LongTermTicket;
import java.time.ZoneId;
import java.time.LocalDate;
import java.awt.Color;


import com.controller.database.DatabaseController;
import com.exceptions.TicketInsertionException;

public class BusBooking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BusBooking.class.getName());
    private final DatabaseController dbc;
    private final String user_type;
    private final String id;
    private final String username;
    /**
     * Creates new form BusBooking
     */
    
    public BusBooking(DatabaseController dbc, String user_type, String id, String username) {
        initComponents();
        setTicketType();
        // ADD DB CONTROLLER
        this.dbc = dbc;
        
        // SET USER INFO
        this.user_type = user_type;
        this.id = id;
        this.username = username;
        
        // HIDE DISCOUNT FOR STUDENTS
        if (user_type.equals("Student")){
            DiscountLabel.setVisible(false);  
        }
        
        // CLOSE BUTTON
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent){
                // Close database controller (if open)
                if (dbc != null){
                    dbc.close();
                }
                dispose();
                System.exit(0);
            }
        });
        

        
    }

    private void setDirandDp(){
        DirectionComboBox.setEnabled(true);
        Calendar.setEnabled(true);
    }
    private void setDpnotDir(){
        DirectionComboBox.setEnabled(false);
        Calendar.setEnabled(true);  
    }
    
    private void setTicketType(){
        DailyButton.addActionListener(e -> setDpnotDir());
        WeeklyButton.addActionListener(e -> setDpnotDir());
        OneWayButton.addActionListener(e -> setDirandDp()); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DestinationComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        DailyButton = new javax.swing.JRadioButton();
        WeeklyButton = new javax.swing.JRadioButton();
        OneWayButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Calendar = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        DirectionComboBox = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DiscountLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 5, true));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUY TICKET");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Target Station:");

        DestinationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Destination", "Turtle Lake", "Hang Xanh", "Binh Trieu", "Binh Phuoc Crossroads", "Binh Duong Aeon Mall", "Becamex Tower" }));
        DestinationComboBox.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ticket Type:");

        buttonGroup1.add(DailyButton);
        DailyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DailyButton.setText("Daily ");

        buttonGroup1.add(WeeklyButton);
        WeeklyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WeeklyButton.setText("Weekly");

        buttonGroup1.add(OneWayButton);
        OneWayButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OneWayButton.setText("One-way");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Go Date:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Direction:");

        DirectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direction", "Morning (From station to VGU)", "Afternoon (From VGU to station)" }));
        DirectionComboBox.setToolTipText("");

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(this::SubmitButtonActionPerformed);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(this::BackButtonActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DiscountLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        DiscountLabel.setForeground(new java.awt.Color(51, 51, 255));
        DiscountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiscountLabel.setText("Professors enjoy 50% off of all purchased tickets!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(226, 226, 226))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SubmitButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BackButton))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(DailyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(WeeklyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OneWayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DirectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(308, 308, 308))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DiscountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DiscountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DailyButton)
                    .addComponent(WeeklyButton)
                    .addComponent(OneWayButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        DailyButton.getAccessibleContext().setAccessibleName("");
        DailyButton.getAccessibleContext().setAccessibleDescription("");
        WeeklyButton.getAccessibleContext().setAccessibleName("");
        WeeklyButton.getAccessibleContext().setAccessibleDescription("");
        OneWayButton.getAccessibleContext().setAccessibleName("");
        OneWayButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // Check validity of submission
        
        // No station error
        if(DestinationComboBox.getSelectedIndex() == 0){
            jLabel6.setText("Please select a target station!");
            jLabel6.setForeground(Color.RED);
            return;
        }
        
        // No ticket type error
        if(!DailyButton.isSelected() && !WeeklyButton.isSelected() && !OneWayButton.isSelected()){
            jLabel6.setText("Please select a ticket type!");
            jLabel6.setForeground(Color.RED);
            return;
        }
        
        // No data choosen
        if (Calendar.getDate() == null) {
            jLabel6.setText("Please select a departure date!");
            jLabel6.setForeground(Color.RED);
            return;
        }
        
        LocalDate selectedDate = Calendar.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        // Date in the past error
        if (selectedDate.isBefore(LocalDate.now())){
            jLabel6.setText("Cannot select a date in the past!");
            jLabel6.setForeground(Color.RED);
            return;
        }
        
        // Not booking ahead error
        if (OneWayButton.isSelected() && selectedDate.isBefore(LocalDate.now().plusDays(3))){
            jLabel6.setText("One way tickets must be booked at least 3 days in advance");
            jLabel6.setForeground(Color.RED);
            return;
        }
        
        
        // No one-way direction error
        if (OneWayButton.isSelected() && DirectionComboBox.getSelectedIndex() == 0) {
            jLabel6.setText("Please specify a direction for one-way ticket!");
            jLabel6.setForeground(Color.RED);
            return;
        }
        
        // Create ticket obj
        Ticket t;
        
        String location = (String) DestinationComboBox.getSelectedItem();
        LocalDate start_date = Calendar.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if (DailyButton.isSelected()){        /*daily*/
            t = LongTermTicket.createDaily(id, start_date, location);
            
        }
        else if (WeeklyButton.isSelected()){    /*weekly*/
            t = LongTermTicket.createWeekly(id, start_date, location);
        }
        else{
            if (DirectionComboBox.getSelectedIndex() == 1){
                t = OneWayTicket.create_FROM(id, start_date, location);
            }
            else{
                t = OneWayTicket.create_TO(id, start_date, location);
            }
        }
        
        
        // Insert ticket obj to db
        try{
            dbc.insert(t);
            jLabel6.setText("Submitted!");
            jLabel6.setForeground(Color.GREEN);
        }
        catch(TicketInsertionException TIe){
            jLabel6.setText(TIe.getMessage());
            jLabel6.setForeground(Color.RED);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UserMenu m = new UserMenu(dbc, user_type, id, username);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_BackButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private com.toedter.calendar.JDateChooser Calendar;
    private javax.swing.JRadioButton DailyButton;
    private javax.swing.JComboBox<String> DestinationComboBox;
    private javax.swing.JComboBox<String> DirectionComboBox;
    private javax.swing.JLabel DiscountLabel;
    private javax.swing.JRadioButton OneWayButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JRadioButton WeeklyButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
