package com.GUI;
/**
 *
 * @author caoda
 */


import com.controller.java.tickets.Ticket;
import com.controller.java.tickets.OneWayTicket;
import com.controller.java.tickets.DailyTicket;
import com.controller.java.tickets.WeeklyTicket;
import java.time.ZoneId;
import java.time.LocalDate;
import java.awt.Color;


import com.controller.database.DatabaseController;
import com.exceptions.TicketInsertionException;

public class BusBooking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BusBooking.class.getName());
    private final DatabaseController dbc;
    private final String id;
    private final String username;
    /**
     * Creates new form BusBooking
     */
    
    public BusBooking(DatabaseController dbc, String id, String username) {
        initComponents();
        setTicketType();

        this.dbc = dbc;
        this.id = id;
        this.username = username;
        
        // CLOSE BUTTON
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent){
                // Close database controller (if open)
                if (dbc != null){
                    dbc.close();
                }
                dispose();
                System.exit(0);
            }
        });
    }

    private void setDirandDp(){
        DirectionComboBox.setEnabled(true);
        jDateChooser1.setEnabled(true);
    }
    private void setDpnotDir(){
        DirectionComboBox.setEnabled(false);
        jDateChooser1.setEnabled(true);  
    }
    
    private void setTicketType(){
        DailyButton.addActionListener(e -> setDpnotDir());
        WeeklyButton.addActionListener(e -> setDpnotDir());
        OneWayButton.addActionListener(e -> setDirandDp()); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DestinationComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        DailyButton = new javax.swing.JRadioButton();
        WeeklyButton = new javax.swing.JRadioButton();
        OneWayButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        DirectionComboBox = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 5, true));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUY TICKET");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Target Station:");

        DestinationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Destination", "Turtle Lake", "Hang Xanh", "Binh Trieu", "Binh Phuoc Crossroads", "Binh Duong Aeon Mall", "Becamex Tower" }));
        DestinationComboBox.setToolTipText("");
        DestinationComboBox.addActionListener(this::DestinationComboBoxActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ticket Type:");

        buttonGroup1.add(DailyButton);
        DailyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DailyButton.setText("Daily ");
        DailyButton.addActionListener(this::DailyButtonActionPerformed);

        buttonGroup1.add(WeeklyButton);
        WeeklyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WeeklyButton.setText("Weekly");
        WeeklyButton.addActionListener(this::WeeklyButtonActionPerformed);

        buttonGroup1.add(OneWayButton);
        OneWayButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OneWayButton.setText("One-way");
        OneWayButton.addActionListener(this::OneWayButtonActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Go Date:");

        jDateChooser1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooser1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Direction:");

        DirectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direction", "Morning (From station to VGU)", "Afternoon (From VGU to station)" }));
        DirectionComboBox.setToolTipText("");
        DirectionComboBox.addActionListener(this::DirectionComboBoxActionPerformed);

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(this::SubmitButtonActionPerformed);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(this::BackButtonActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SubmitButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BackButton))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(DailyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(WeeklyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OneWayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DirectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(308, 308, 308))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(226, 226, 226))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DailyButton)
                    .addComponent(WeeklyButton)
                    .addComponent(OneWayButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        DailyButton.getAccessibleContext().setAccessibleName("");
        DailyButton.getAccessibleContext().setAccessibleDescription("");
        WeeklyButton.getAccessibleContext().setAccessibleName("");
        WeeklyButton.getAccessibleContext().setAccessibleDescription("");
        OneWayButton.getAccessibleContext().setAccessibleName("");
        OneWayButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DestinationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinationComboBoxActionPerformed

    private void DailyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DailyButtonActionPerformed

    private void WeeklyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeklyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeeklyButtonActionPerformed

    private void OneWayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneWayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OneWayButtonActionPerformed

    private void DirectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirectionComboBoxActionPerformed

    private int SubmitConditions(){
        // Conditions before submission
        if(DestinationComboBox.getSelectedIndex() == 0){
            return 1;
        }
        
        if(!DailyButton.isSelected() && !WeeklyButton.isSelected() && !OneWayButton.isSelected()){
            return 2;
        }
        
        if (jDateChooser1.getDate() == null) {
            return 3;
            }
        
        if (OneWayButton.isSelected() && DirectionComboBox.getSelectedIndex() == 0) {
            return 4;
        }
        
        // Only accept oneway tickets booked at least 3 days in advance
        LocalDate selectedDate = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate threeDaysLater = LocalDate.now().plusDays(3);
        
        if (OneWayButton.isSelected() && selectedDate.isBefore(threeDaysLater)){
            return 5;
        }
        return 0;
    }
    
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // Check validity of submission
        int submission_status = SubmitConditions();
        
        switch (submission_status){
            case 1:
                jLabel6.setText("Please select a target station!");
                jLabel6.setForeground(Color.RED);
                return;
            case 2:
                jLabel6.setText("Please select a ticket type!");
                jLabel6.setForeground(Color.RED);
                return;
            case 3:
                jLabel6.setText("Please select a departure date!");
                jLabel6.setForeground(Color.RED);
                return;
            case 4:
                jLabel6.setText("Please select a direction for one-way ticket!");
                jLabel6.setForeground(Color.RED);
                return;
            case 5:
                jLabel6.setText("One way tickets must be booked at least 3 days in advance");
                jLabel6.setForeground(Color.RED);
                return;
            default:
        }
        
        // Create ticket obj
        Ticket t;
        
        String location = (String) DestinationComboBox.getSelectedItem();
        LocalDate start_date = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if (DailyButton.isSelected()){        /*daily*/
            t = DailyTicket.create(id, start_date, location);
            
        }
        else if (WeeklyButton.isSelected()){    /*weekly*/
            t = WeeklyTicket.create(id, start_date, location);
        }
        else{
            String direction = (DirectionComboBox.getSelectedIndex() == 1) ? "T" : "F";    /* Determine direction*/
            t = OneWayTicket.create(id, start_date, location, direction);
        }
        
        
        // Insert ticket obj to db
        try{
            dbc.insert(t);
            jLabel6.setText("Submitted!");
            jLabel6.setForeground(Color.GREEN);
        }
        catch(TicketInsertionException TIe){
            jLabel6.setText(TIe.getMessage());
            jLabel6.setForeground(Color.RED);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UserMenu m = new UserMenu(dbc, id, username);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jDateChooser1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1AncestorAdded

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton DailyButton;
    private javax.swing.JComboBox<String> DestinationComboBox;
    private javax.swing.JComboBox<String> DirectionComboBox;
    private javax.swing.JRadioButton OneWayButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JRadioButton WeeklyButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
